// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ent "github.com/np-inprove/server/internal/ent"
	entityinstitution "github.com/np-inprove/server/internal/entity/institution"

	mock "github.com/stretchr/testify/mock"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// CreateInstitution provides a mock function with given fields: ctx, name, shortName, description
func (_m *MockWriter) CreateInstitution(ctx context.Context, name string, shortName string, description string) (*ent.Institution, error) {
	ret := _m.Called(ctx, name, shortName, description)

	var r0 *ent.Institution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*ent.Institution, error)); ok {
		return rf(ctx, name, shortName, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *ent.Institution); ok {
		r0 = rf(ctx, name, shortName, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Institution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, shortName, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWriter_CreateInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstitution'
type MockWriter_CreateInstitution_Call struct {
	*mock.Call
}

// CreateInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - shortName string
//   - description string
func (_e *MockWriter_Expecter) CreateInstitution(ctx interface{}, name interface{}, shortName interface{}, description interface{}) *MockWriter_CreateInstitution_Call {
	return &MockWriter_CreateInstitution_Call{Call: _e.mock.On("CreateInstitution", ctx, name, shortName, description)}
}

func (_c *MockWriter_CreateInstitution_Call) Run(run func(ctx context.Context, name string, shortName string, description string)) *MockWriter_CreateInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockWriter_CreateInstitution_Call) Return(_a0 *ent.Institution, _a1 error) *MockWriter_CreateInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWriter_CreateInstitution_Call) RunAndReturn(run func(context.Context, string, string, string) (*ent.Institution, error)) *MockWriter_CreateInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInviteLink provides a mock function with given fields: ctx, id, code, role
func (_m *MockWriter) CreateInviteLink(ctx context.Context, id int, code string, role entityinstitution.Role) (*ent.InstitutionInviteLink, error) {
	ret := _m.Called(ctx, id, code, role)

	var r0 *ent.InstitutionInviteLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, entityinstitution.Role) (*ent.InstitutionInviteLink, error)); ok {
		return rf(ctx, id, code, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, entityinstitution.Role) *ent.InstitutionInviteLink); ok {
		r0 = rf(ctx, id, code, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.InstitutionInviteLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, entityinstitution.Role) error); ok {
		r1 = rf(ctx, id, code, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWriter_CreateInviteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInviteLink'
type MockWriter_CreateInviteLink_Call struct {
	*mock.Call
}

// CreateInviteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - code string
//   - role entityinstitution.Role
func (_e *MockWriter_Expecter) CreateInviteLink(ctx interface{}, id interface{}, code interface{}, role interface{}) *MockWriter_CreateInviteLink_Call {
	return &MockWriter_CreateInviteLink_Call{Call: _e.mock.On("CreateInviteLink", ctx, id, code, role)}
}

func (_c *MockWriter_CreateInviteLink_Call) Run(run func(ctx context.Context, id int, code string, role entityinstitution.Role)) *MockWriter_CreateInviteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(entityinstitution.Role))
	})
	return _c
}

func (_c *MockWriter_CreateInviteLink_Call) Return(_a0 *ent.InstitutionInviteLink, _a1 error) *MockWriter_CreateInviteLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWriter_CreateInviteLink_Call) RunAndReturn(run func(context.Context, int, string, entityinstitution.Role) (*ent.InstitutionInviteLink, error)) *MockWriter_CreateInviteLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInstitution provides a mock function with given fields: ctx, id
func (_m *MockWriter) DeleteInstitution(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_DeleteInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstitution'
type MockWriter_DeleteInstitution_Call struct {
	*mock.Call
}

// DeleteInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockWriter_Expecter) DeleteInstitution(ctx interface{}, id interface{}) *MockWriter_DeleteInstitution_Call {
	return &MockWriter_DeleteInstitution_Call{Call: _e.mock.On("DeleteInstitution", ctx, id)}
}

func (_c *MockWriter_DeleteInstitution_Call) Run(run func(ctx context.Context, id int)) *MockWriter_DeleteInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockWriter_DeleteInstitution_Call) Return(_a0 error) *MockWriter_DeleteInstitution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_DeleteInstitution_Call) RunAndReturn(run func(context.Context, int) error) *MockWriter_DeleteInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInviteLink provides a mock function with given fields: ctx, id
func (_m *MockWriter) DeleteInviteLink(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_DeleteInviteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInviteLink'
type MockWriter_DeleteInviteLink_Call struct {
	*mock.Call
}

// DeleteInviteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockWriter_Expecter) DeleteInviteLink(ctx interface{}, id interface{}) *MockWriter_DeleteInviteLink_Call {
	return &MockWriter_DeleteInviteLink_Call{Call: _e.mock.On("DeleteInviteLink", ctx, id)}
}

func (_c *MockWriter_DeleteInviteLink_Call) Run(run func(ctx context.Context, id int)) *MockWriter_DeleteInviteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockWriter_DeleteInviteLink_Call) Return(_a0 error) *MockWriter_DeleteInviteLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_DeleteInviteLink_Call) RunAndReturn(run func(context.Context, int) error) *MockWriter_DeleteInviteLink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInstitution provides a mock function with given fields: ctx, id, name, shortName, description
func (_m *MockWriter) UpdateInstitution(ctx context.Context, id int, name string, shortName string, description string) (*ent.Institution, error) {
	ret := _m.Called(ctx, id, name, shortName, description)

	var r0 *ent.Institution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, string) (*ent.Institution, error)); ok {
		return rf(ctx, id, name, shortName, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, string) *ent.Institution); ok {
		r0 = rf(ctx, id, name, shortName, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Institution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string, string) error); ok {
		r1 = rf(ctx, id, name, shortName, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWriter_UpdateInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInstitution'
type MockWriter_UpdateInstitution_Call struct {
	*mock.Call
}

// UpdateInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - name string
//   - shortName string
//   - description string
func (_e *MockWriter_Expecter) UpdateInstitution(ctx interface{}, id interface{}, name interface{}, shortName interface{}, description interface{}) *MockWriter_UpdateInstitution_Call {
	return &MockWriter_UpdateInstitution_Call{Call: _e.mock.On("UpdateInstitution", ctx, id, name, shortName, description)}
}

func (_c *MockWriter_UpdateInstitution_Call) Run(run func(ctx context.Context, id int, name string, shortName string, description string)) *MockWriter_UpdateInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockWriter_UpdateInstitution_Call) Return(_a0 *ent.Institution, _a1 error) *MockWriter_UpdateInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWriter_UpdateInstitution_Call) RunAndReturn(run func(context.Context, int, string, string, string) (*ent.Institution, error)) *MockWriter_UpdateInstitution_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockWriter(t mockConstructorTestingTNewMockWriter) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
