packages:
  github.com/np-inprove/server/internal/ent: # Ignore folder in generation
  github.com/np-inprove/server/internal/entity/group: # Ignore folder in generation
  github.com/np-inprove/server/internal/entity/user: # Ignore folder in generation
  github.com/np-inprove/server/internal:
    config:
      all: True
      recursive: True
      with-expecter: True
      outpkg: mocks
      filename: "mock_{{.InterfaceNameSnake}}.go"
      dir: "{{.InterfaceDir}}/mocks"
