// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/np-inprove/server/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/np-inprove/server/internal/ent/academicschool"
	"github.com/np-inprove/server/internal/ent/course"
	"github.com/np-inprove/server/internal/ent/institution"
	"github.com/np-inprove/server/internal/ent/pet"
	"github.com/np-inprove/server/internal/ent/prize"
	"github.com/np-inprove/server/internal/ent/prizeredemptions"
	"github.com/np-inprove/server/internal/ent/user"
	"github.com/np-inprove/server/internal/ent/userpet"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AcademicSchool is the client for interacting with the AcademicSchool builders.
	AcademicSchool *AcademicSchoolClient
	// Course is the client for interacting with the Course builders.
	Course *CourseClient
	// Institution is the client for interacting with the Institution builders.
	Institution *InstitutionClient
	// Pet is the client for interacting with the Pet builders.
	Pet *PetClient
	// Prize is the client for interacting with the Prize builders.
	Prize *PrizeClient
	// PrizeRedemptions is the client for interacting with the PrizeRedemptions builders.
	PrizeRedemptions *PrizeRedemptionsClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserPet is the client for interacting with the UserPet builders.
	UserPet *UserPetClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AcademicSchool = NewAcademicSchoolClient(c.config)
	c.Course = NewCourseClient(c.config)
	c.Institution = NewInstitutionClient(c.config)
	c.Pet = NewPetClient(c.config)
	c.Prize = NewPrizeClient(c.config)
	c.PrizeRedemptions = NewPrizeRedemptionsClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserPet = NewUserPetClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AcademicSchool:   NewAcademicSchoolClient(cfg),
		Course:           NewCourseClient(cfg),
		Institution:      NewInstitutionClient(cfg),
		Pet:              NewPetClient(cfg),
		Prize:            NewPrizeClient(cfg),
		PrizeRedemptions: NewPrizeRedemptionsClient(cfg),
		User:             NewUserClient(cfg),
		UserPet:          NewUserPetClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AcademicSchool:   NewAcademicSchoolClient(cfg),
		Course:           NewCourseClient(cfg),
		Institution:      NewInstitutionClient(cfg),
		Pet:              NewPetClient(cfg),
		Prize:            NewPrizeClient(cfg),
		PrizeRedemptions: NewPrizeRedemptionsClient(cfg),
		User:             NewUserClient(cfg),
		UserPet:          NewUserPetClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AcademicSchool.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AcademicSchool, c.Course, c.Institution, c.Pet, c.Prize, c.PrizeRedemptions,
		c.User, c.UserPet,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AcademicSchool, c.Course, c.Institution, c.Pet, c.Prize, c.PrizeRedemptions,
		c.User, c.UserPet,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AcademicSchoolMutation:
		return c.AcademicSchool.mutate(ctx, m)
	case *CourseMutation:
		return c.Course.mutate(ctx, m)
	case *InstitutionMutation:
		return c.Institution.mutate(ctx, m)
	case *PetMutation:
		return c.Pet.mutate(ctx, m)
	case *PrizeMutation:
		return c.Prize.mutate(ctx, m)
	case *PrizeRedemptionsMutation:
		return c.PrizeRedemptions.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserPetMutation:
		return c.UserPet.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AcademicSchoolClient is a client for the AcademicSchool schema.
type AcademicSchoolClient struct {
	config
}

// NewAcademicSchoolClient returns a client for the AcademicSchool from the given config.
func NewAcademicSchoolClient(c config) *AcademicSchoolClient {
	return &AcademicSchoolClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `academicschool.Hooks(f(g(h())))`.
func (c *AcademicSchoolClient) Use(hooks ...Hook) {
	c.hooks.AcademicSchool = append(c.hooks.AcademicSchool, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `academicschool.Intercept(f(g(h())))`.
func (c *AcademicSchoolClient) Intercept(interceptors ...Interceptor) {
	c.inters.AcademicSchool = append(c.inters.AcademicSchool, interceptors...)
}

// Create returns a builder for creating a AcademicSchool entity.
func (c *AcademicSchoolClient) Create() *AcademicSchoolCreate {
	mutation := newAcademicSchoolMutation(c.config, OpCreate)
	return &AcademicSchoolCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AcademicSchool entities.
func (c *AcademicSchoolClient) CreateBulk(builders ...*AcademicSchoolCreate) *AcademicSchoolCreateBulk {
	return &AcademicSchoolCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AcademicSchool.
func (c *AcademicSchoolClient) Update() *AcademicSchoolUpdate {
	mutation := newAcademicSchoolMutation(c.config, OpUpdate)
	return &AcademicSchoolUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AcademicSchoolClient) UpdateOne(as *AcademicSchool) *AcademicSchoolUpdateOne {
	mutation := newAcademicSchoolMutation(c.config, OpUpdateOne, withAcademicSchool(as))
	return &AcademicSchoolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AcademicSchoolClient) UpdateOneID(id int) *AcademicSchoolUpdateOne {
	mutation := newAcademicSchoolMutation(c.config, OpUpdateOne, withAcademicSchoolID(id))
	return &AcademicSchoolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AcademicSchool.
func (c *AcademicSchoolClient) Delete() *AcademicSchoolDelete {
	mutation := newAcademicSchoolMutation(c.config, OpDelete)
	return &AcademicSchoolDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AcademicSchoolClient) DeleteOne(as *AcademicSchool) *AcademicSchoolDeleteOne {
	return c.DeleteOneID(as.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AcademicSchoolClient) DeleteOneID(id int) *AcademicSchoolDeleteOne {
	builder := c.Delete().Where(academicschool.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AcademicSchoolDeleteOne{builder}
}

// Query returns a query builder for AcademicSchool.
func (c *AcademicSchoolClient) Query() *AcademicSchoolQuery {
	return &AcademicSchoolQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAcademicSchool},
		inters: c.Interceptors(),
	}
}

// Get returns a AcademicSchool entity by its id.
func (c *AcademicSchoolClient) Get(ctx context.Context, id int) (*AcademicSchool, error) {
	return c.Query().Where(academicschool.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AcademicSchoolClient) GetX(ctx context.Context, id int) *AcademicSchool {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInstitution queries the institution edge of a AcademicSchool.
func (c *AcademicSchoolClient) QueryInstitution(as *AcademicSchool) *InstitutionQuery {
	query := (&InstitutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := as.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(academicschool.Table, academicschool.FieldID, id),
			sqlgraph.To(institution.Table, institution.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, academicschool.InstitutionTable, academicschool.InstitutionColumn),
		)
		fromV = sqlgraph.Neighbors(as.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCourses queries the courses edge of a AcademicSchool.
func (c *AcademicSchoolClient) QueryCourses(as *AcademicSchool) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := as.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(academicschool.Table, academicschool.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, academicschool.CoursesTable, academicschool.CoursesColumn),
		)
		fromV = sqlgraph.Neighbors(as.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AcademicSchoolClient) Hooks() []Hook {
	return c.hooks.AcademicSchool
}

// Interceptors returns the client interceptors.
func (c *AcademicSchoolClient) Interceptors() []Interceptor {
	return c.inters.AcademicSchool
}

func (c *AcademicSchoolClient) mutate(ctx context.Context, m *AcademicSchoolMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AcademicSchoolCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AcademicSchoolUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AcademicSchoolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AcademicSchoolDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AcademicSchool mutation op: %q", m.Op())
	}
}

// CourseClient is a client for the Course schema.
type CourseClient struct {
	config
}

// NewCourseClient returns a client for the Course from the given config.
func NewCourseClient(c config) *CourseClient {
	return &CourseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `course.Hooks(f(g(h())))`.
func (c *CourseClient) Use(hooks ...Hook) {
	c.hooks.Course = append(c.hooks.Course, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `course.Intercept(f(g(h())))`.
func (c *CourseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Course = append(c.inters.Course, interceptors...)
}

// Create returns a builder for creating a Course entity.
func (c *CourseClient) Create() *CourseCreate {
	mutation := newCourseMutation(c.config, OpCreate)
	return &CourseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Course entities.
func (c *CourseClient) CreateBulk(builders ...*CourseCreate) *CourseCreateBulk {
	return &CourseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Course.
func (c *CourseClient) Update() *CourseUpdate {
	mutation := newCourseMutation(c.config, OpUpdate)
	return &CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseClient) UpdateOne(co *Course) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourse(co))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseClient) UpdateOneID(id int) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourseID(id))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Course.
func (c *CourseClient) Delete() *CourseDelete {
	mutation := newCourseMutation(c.config, OpDelete)
	return &CourseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseClient) DeleteOne(co *Course) *CourseDeleteOne {
	return c.DeleteOneID(co.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CourseClient) DeleteOneID(id int) *CourseDeleteOne {
	builder := c.Delete().Where(course.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseDeleteOne{builder}
}

// Query returns a query builder for Course.
func (c *CourseClient) Query() *CourseQuery {
	return &CourseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCourse},
		inters: c.Interceptors(),
	}
}

// Get returns a Course entity by its id.
func (c *CourseClient) Get(ctx context.Context, id int) (*Course, error) {
	return c.Query().Where(course.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseClient) GetX(ctx context.Context, id int) *Course {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStudents queries the students edge of a Course.
func (c *CourseClient) QueryStudents(co *Course) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.StudentsTable, course.StudentsColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAcademicSchool queries the academic_school edge of a Course.
func (c *CourseClient) QueryAcademicSchool(co *Course) *AcademicSchoolQuery {
	query := (&AcademicSchoolClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(academicschool.Table, academicschool.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, course.AcademicSchoolTable, course.AcademicSchoolColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CourseClient) Hooks() []Hook {
	return c.hooks.Course
}

// Interceptors returns the client interceptors.
func (c *CourseClient) Interceptors() []Interceptor {
	return c.inters.Course
}

func (c *CourseClient) mutate(ctx context.Context, m *CourseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CourseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CourseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Course mutation op: %q", m.Op())
	}
}

// InstitutionClient is a client for the Institution schema.
type InstitutionClient struct {
	config
}

// NewInstitutionClient returns a client for the Institution from the given config.
func NewInstitutionClient(c config) *InstitutionClient {
	return &InstitutionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `institution.Hooks(f(g(h())))`.
func (c *InstitutionClient) Use(hooks ...Hook) {
	c.hooks.Institution = append(c.hooks.Institution, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `institution.Intercept(f(g(h())))`.
func (c *InstitutionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Institution = append(c.inters.Institution, interceptors...)
}

// Create returns a builder for creating a Institution entity.
func (c *InstitutionClient) Create() *InstitutionCreate {
	mutation := newInstitutionMutation(c.config, OpCreate)
	return &InstitutionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Institution entities.
func (c *InstitutionClient) CreateBulk(builders ...*InstitutionCreate) *InstitutionCreateBulk {
	return &InstitutionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Institution.
func (c *InstitutionClient) Update() *InstitutionUpdate {
	mutation := newInstitutionMutation(c.config, OpUpdate)
	return &InstitutionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InstitutionClient) UpdateOne(i *Institution) *InstitutionUpdateOne {
	mutation := newInstitutionMutation(c.config, OpUpdateOne, withInstitution(i))
	return &InstitutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InstitutionClient) UpdateOneID(id int) *InstitutionUpdateOne {
	mutation := newInstitutionMutation(c.config, OpUpdateOne, withInstitutionID(id))
	return &InstitutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Institution.
func (c *InstitutionClient) Delete() *InstitutionDelete {
	mutation := newInstitutionMutation(c.config, OpDelete)
	return &InstitutionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InstitutionClient) DeleteOne(i *Institution) *InstitutionDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InstitutionClient) DeleteOneID(id int) *InstitutionDeleteOne {
	builder := c.Delete().Where(institution.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InstitutionDeleteOne{builder}
}

// Query returns a query builder for Institution.
func (c *InstitutionClient) Query() *InstitutionQuery {
	return &InstitutionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInstitution},
		inters: c.Interceptors(),
	}
}

// Get returns a Institution entity by its id.
func (c *InstitutionClient) Get(ctx context.Context, id int) (*Institution, error) {
	return c.Query().Where(institution.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InstitutionClient) GetX(ctx context.Context, id int) *Institution {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAdmins queries the admins edge of a Institution.
func (c *InstitutionClient) QueryAdmins(i *Institution) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(institution.Table, institution.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, institution.AdminsTable, institution.AdminsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPrizes queries the prizes edge of a Institution.
func (c *InstitutionClient) QueryPrizes(i *Institution) *PrizeQuery {
	query := (&PrizeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(institution.Table, institution.FieldID, id),
			sqlgraph.To(prize.Table, prize.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, institution.PrizesTable, institution.PrizesColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAcademicSchools queries the academic_schools edge of a Institution.
func (c *InstitutionClient) QueryAcademicSchools(i *Institution) *AcademicSchoolQuery {
	query := (&AcademicSchoolClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(institution.Table, institution.FieldID, id),
			sqlgraph.To(academicschool.Table, academicschool.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, institution.AcademicSchoolsTable, institution.AcademicSchoolsColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InstitutionClient) Hooks() []Hook {
	return c.hooks.Institution
}

// Interceptors returns the client interceptors.
func (c *InstitutionClient) Interceptors() []Interceptor {
	return c.inters.Institution
}

func (c *InstitutionClient) mutate(ctx context.Context, m *InstitutionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InstitutionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InstitutionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InstitutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InstitutionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Institution mutation op: %q", m.Op())
	}
}

// PetClient is a client for the Pet schema.
type PetClient struct {
	config
}

// NewPetClient returns a client for the Pet from the given config.
func NewPetClient(c config) *PetClient {
	return &PetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pet.Hooks(f(g(h())))`.
func (c *PetClient) Use(hooks ...Hook) {
	c.hooks.Pet = append(c.hooks.Pet, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pet.Intercept(f(g(h())))`.
func (c *PetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pet = append(c.inters.Pet, interceptors...)
}

// Create returns a builder for creating a Pet entity.
func (c *PetClient) Create() *PetCreate {
	mutation := newPetMutation(c.config, OpCreate)
	return &PetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pet entities.
func (c *PetClient) CreateBulk(builders ...*PetCreate) *PetCreateBulk {
	return &PetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pet.
func (c *PetClient) Update() *PetUpdate {
	mutation := newPetMutation(c.config, OpUpdate)
	return &PetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PetClient) UpdateOne(pe *Pet) *PetUpdateOne {
	mutation := newPetMutation(c.config, OpUpdateOne, withPet(pe))
	return &PetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PetClient) UpdateOneID(id int) *PetUpdateOne {
	mutation := newPetMutation(c.config, OpUpdateOne, withPetID(id))
	return &PetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pet.
func (c *PetClient) Delete() *PetDelete {
	mutation := newPetMutation(c.config, OpDelete)
	return &PetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PetClient) DeleteOne(pe *Pet) *PetDeleteOne {
	return c.DeleteOneID(pe.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PetClient) DeleteOneID(id int) *PetDeleteOne {
	builder := c.Delete().Where(pet.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PetDeleteOne{builder}
}

// Query returns a query builder for Pet.
func (c *PetClient) Query() *PetQuery {
	return &PetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePet},
		inters: c.Interceptors(),
	}
}

// Get returns a Pet entity by its id.
func (c *PetClient) Get(ctx context.Context, id int) (*Pet, error) {
	return c.Query().Where(pet.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PetClient) GetX(ctx context.Context, id int) *Pet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Pet.
func (c *PetClient) QueryOwner(pe *Pet) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pe.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, pet.OwnerTable, pet.OwnerPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(pe.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserPet queries the user_pet edge of a Pet.
func (c *PetClient) QueryUserPet(pe *Pet) *UserPetQuery {
	query := (&UserPetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pe.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(userpet.Table, userpet.PetColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, pet.UserPetTable, pet.UserPetColumn),
		)
		fromV = sqlgraph.Neighbors(pe.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PetClient) Hooks() []Hook {
	return c.hooks.Pet
}

// Interceptors returns the client interceptors.
func (c *PetClient) Interceptors() []Interceptor {
	return c.inters.Pet
}

func (c *PetClient) mutate(ctx context.Context, m *PetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pet mutation op: %q", m.Op())
	}
}

// PrizeClient is a client for the Prize schema.
type PrizeClient struct {
	config
}

// NewPrizeClient returns a client for the Prize from the given config.
func NewPrizeClient(c config) *PrizeClient {
	return &PrizeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prize.Hooks(f(g(h())))`.
func (c *PrizeClient) Use(hooks ...Hook) {
	c.hooks.Prize = append(c.hooks.Prize, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `prize.Intercept(f(g(h())))`.
func (c *PrizeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Prize = append(c.inters.Prize, interceptors...)
}

// Create returns a builder for creating a Prize entity.
func (c *PrizeClient) Create() *PrizeCreate {
	mutation := newPrizeMutation(c.config, OpCreate)
	return &PrizeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Prize entities.
func (c *PrizeClient) CreateBulk(builders ...*PrizeCreate) *PrizeCreateBulk {
	return &PrizeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Prize.
func (c *PrizeClient) Update() *PrizeUpdate {
	mutation := newPrizeMutation(c.config, OpUpdate)
	return &PrizeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PrizeClient) UpdateOne(pr *Prize) *PrizeUpdateOne {
	mutation := newPrizeMutation(c.config, OpUpdateOne, withPrize(pr))
	return &PrizeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PrizeClient) UpdateOneID(id int) *PrizeUpdateOne {
	mutation := newPrizeMutation(c.config, OpUpdateOne, withPrizeID(id))
	return &PrizeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Prize.
func (c *PrizeClient) Delete() *PrizeDelete {
	mutation := newPrizeMutation(c.config, OpDelete)
	return &PrizeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PrizeClient) DeleteOne(pr *Prize) *PrizeDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PrizeClient) DeleteOneID(id int) *PrizeDeleteOne {
	builder := c.Delete().Where(prize.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PrizeDeleteOne{builder}
}

// Query returns a query builder for Prize.
func (c *PrizeClient) Query() *PrizeQuery {
	return &PrizeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePrize},
		inters: c.Interceptors(),
	}
}

// Get returns a Prize entity by its id.
func (c *PrizeClient) Get(ctx context.Context, id int) (*Prize, error) {
	return c.Query().Where(prize.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PrizeClient) GetX(ctx context.Context, id int) *Prize {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInstitution queries the institution edge of a Prize.
func (c *PrizeClient) QueryInstitution(pr *Prize) *InstitutionQuery {
	query := (&InstitutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(prize.Table, prize.FieldID, id),
			sqlgraph.To(institution.Table, institution.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, prize.InstitutionTable, prize.InstitutionColumn),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRedemptionUsers queries the redemption_users edge of a Prize.
func (c *PrizeClient) QueryRedemptionUsers(pr *Prize) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(prize.Table, prize.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, prize.RedemptionUsersTable, prize.RedemptionUsersPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPrizeRedemptions queries the prize_redemptions edge of a Prize.
func (c *PrizeClient) QueryPrizeRedemptions(pr *Prize) *PrizeRedemptionsQuery {
	query := (&PrizeRedemptionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(prize.Table, prize.FieldID, id),
			sqlgraph.To(prizeredemptions.Table, prizeredemptions.PrizeColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, prize.PrizeRedemptionsTable, prize.PrizeRedemptionsColumn),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PrizeClient) Hooks() []Hook {
	return c.hooks.Prize
}

// Interceptors returns the client interceptors.
func (c *PrizeClient) Interceptors() []Interceptor {
	return c.inters.Prize
}

func (c *PrizeClient) mutate(ctx context.Context, m *PrizeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PrizeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PrizeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PrizeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PrizeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Prize mutation op: %q", m.Op())
	}
}

// PrizeRedemptionsClient is a client for the PrizeRedemptions schema.
type PrizeRedemptionsClient struct {
	config
}

// NewPrizeRedemptionsClient returns a client for the PrizeRedemptions from the given config.
func NewPrizeRedemptionsClient(c config) *PrizeRedemptionsClient {
	return &PrizeRedemptionsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prizeredemptions.Hooks(f(g(h())))`.
func (c *PrizeRedemptionsClient) Use(hooks ...Hook) {
	c.hooks.PrizeRedemptions = append(c.hooks.PrizeRedemptions, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `prizeredemptions.Intercept(f(g(h())))`.
func (c *PrizeRedemptionsClient) Intercept(interceptors ...Interceptor) {
	c.inters.PrizeRedemptions = append(c.inters.PrizeRedemptions, interceptors...)
}

// Create returns a builder for creating a PrizeRedemptions entity.
func (c *PrizeRedemptionsClient) Create() *PrizeRedemptionsCreate {
	mutation := newPrizeRedemptionsMutation(c.config, OpCreate)
	return &PrizeRedemptionsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PrizeRedemptions entities.
func (c *PrizeRedemptionsClient) CreateBulk(builders ...*PrizeRedemptionsCreate) *PrizeRedemptionsCreateBulk {
	return &PrizeRedemptionsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PrizeRedemptions.
func (c *PrizeRedemptionsClient) Update() *PrizeRedemptionsUpdate {
	mutation := newPrizeRedemptionsMutation(c.config, OpUpdate)
	return &PrizeRedemptionsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PrizeRedemptionsClient) UpdateOne(pr *PrizeRedemptions) *PrizeRedemptionsUpdateOne {
	mutation := newPrizeRedemptionsMutation(c.config, OpUpdateOne)
	mutation.prize = &pr.PrizeID
	mutation.user = &pr.UserID
	return &PrizeRedemptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PrizeRedemptions.
func (c *PrizeRedemptionsClient) Delete() *PrizeRedemptionsDelete {
	mutation := newPrizeRedemptionsMutation(c.config, OpDelete)
	return &PrizeRedemptionsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for PrizeRedemptions.
func (c *PrizeRedemptionsClient) Query() *PrizeRedemptionsQuery {
	return &PrizeRedemptionsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePrizeRedemptions},
		inters: c.Interceptors(),
	}
}

// QueryPrize queries the prize edge of a PrizeRedemptions.
func (c *PrizeRedemptionsClient) QueryPrize(pr *PrizeRedemptions) *PrizeQuery {
	return c.Query().
		Where(prizeredemptions.PrizeID(pr.PrizeID), prizeredemptions.UserID(pr.UserID)).
		QueryPrize()
}

// QueryUser queries the user edge of a PrizeRedemptions.
func (c *PrizeRedemptionsClient) QueryUser(pr *PrizeRedemptions) *UserQuery {
	return c.Query().
		Where(prizeredemptions.PrizeID(pr.PrizeID), prizeredemptions.UserID(pr.UserID)).
		QueryUser()
}

// Hooks returns the client hooks.
func (c *PrizeRedemptionsClient) Hooks() []Hook {
	return c.hooks.PrizeRedemptions
}

// Interceptors returns the client interceptors.
func (c *PrizeRedemptionsClient) Interceptors() []Interceptor {
	return c.inters.PrizeRedemptions
}

func (c *PrizeRedemptionsClient) mutate(ctx context.Context, m *PrizeRedemptionsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PrizeRedemptionsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PrizeRedemptionsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PrizeRedemptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PrizeRedemptionsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PrizeRedemptions mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInstitution queries the institution edge of a User.
func (c *UserClient) QueryInstitution(u *User) *InstitutionQuery {
	query := (&InstitutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(institution.Table, institution.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.InstitutionTable, user.InstitutionPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCourse queries the course edge of a User.
func (c *UserClient) QueryCourse(u *User) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.CourseTable, user.CourseColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPrize queries the prize edge of a User.
func (c *UserClient) QueryPrize(u *User) *PrizeQuery {
	query := (&PrizeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(prize.Table, prize.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.PrizeTable, user.PrizePrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPet queries the pet edge of a User.
func (c *UserClient) QueryPet(u *User) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.PetTable, user.PetPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPrizeRedemptions queries the prize_redemptions edge of a User.
func (c *UserClient) QueryPrizeRedemptions(u *User) *PrizeRedemptionsQuery {
	query := (&PrizeRedemptionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(prizeredemptions.Table, prizeredemptions.UserColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, user.PrizeRedemptionsTable, user.PrizeRedemptionsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserPet queries the user_pet edge of a User.
func (c *UserClient) QueryUserPet(u *User) *UserPetQuery {
	query := (&UserPetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(userpet.Table, userpet.UserColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, user.UserPetTable, user.UserPetColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserPetClient is a client for the UserPet schema.
type UserPetClient struct {
	config
}

// NewUserPetClient returns a client for the UserPet from the given config.
func NewUserPetClient(c config) *UserPetClient {
	return &UserPetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userpet.Hooks(f(g(h())))`.
func (c *UserPetClient) Use(hooks ...Hook) {
	c.hooks.UserPet = append(c.hooks.UserPet, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userpet.Intercept(f(g(h())))`.
func (c *UserPetClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserPet = append(c.inters.UserPet, interceptors...)
}

// Create returns a builder for creating a UserPet entity.
func (c *UserPetClient) Create() *UserPetCreate {
	mutation := newUserPetMutation(c.config, OpCreate)
	return &UserPetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserPet entities.
func (c *UserPetClient) CreateBulk(builders ...*UserPetCreate) *UserPetCreateBulk {
	return &UserPetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserPet.
func (c *UserPetClient) Update() *UserPetUpdate {
	mutation := newUserPetMutation(c.config, OpUpdate)
	return &UserPetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserPetClient) UpdateOne(up *UserPet) *UserPetUpdateOne {
	mutation := newUserPetMutation(c.config, OpUpdateOne)
	mutation.pet = &up.PetID
	mutation.user = &up.UserID
	return &UserPetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserPet.
func (c *UserPetClient) Delete() *UserPetDelete {
	mutation := newUserPetMutation(c.config, OpDelete)
	return &UserPetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for UserPet.
func (c *UserPetClient) Query() *UserPetQuery {
	return &UserPetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserPet},
		inters: c.Interceptors(),
	}
}

// QueryPet queries the pet edge of a UserPet.
func (c *UserPetClient) QueryPet(up *UserPet) *PetQuery {
	return c.Query().
		Where(userpet.PetID(up.PetID), userpet.UserID(up.UserID)).
		QueryPet()
}

// QueryUser queries the user edge of a UserPet.
func (c *UserPetClient) QueryUser(up *UserPet) *UserQuery {
	return c.Query().
		Where(userpet.PetID(up.PetID), userpet.UserID(up.UserID)).
		QueryUser()
}

// Hooks returns the client hooks.
func (c *UserPetClient) Hooks() []Hook {
	return c.hooks.UserPet
}

// Interceptors returns the client interceptors.
func (c *UserPetClient) Interceptors() []Interceptor {
	return c.inters.UserPet
}

func (c *UserPetClient) mutate(ctx context.Context, m *UserPetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserPetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserPetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserPetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserPetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserPet mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AcademicSchool, Course, Institution, Pet, Prize, PrizeRedemptions, User,
		UserPet []ent.Hook
	}
	inters struct {
		AcademicSchool, Course, Institution, Pet, Prize, PrizeRedemptions, User,
		UserPet []ent.Interceptor
	}
)
