// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AcademicSchool is the predicate function for academicschool builders.
type AcademicSchool func(*sql.Selector)

// Accessory is the predicate function for accessory builders.
type Accessory func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Deadline is the predicate function for deadline builders.
type Deadline func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// ForumPost is the predicate function for forumpost builders.
type ForumPost func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupUser is the predicate function for groupuser builders.
type GroupUser func(*sql.Selector)

// Institution is the predicate function for institution builders.
type Institution func(*sql.Selector)

// JWTRevocation is the predicate function for jwtrevocation builders.
type JWTRevocation func(*sql.Selector)

// Milestone is the predicate function for milestone builders.
type Milestone func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// Reaction is the predicate function for reaction builders.
type Reaction func(*sql.Selector)

// Redemption is the predicate function for redemption builders.
type Redemption func(*sql.Selector)

// StudyPlan is the predicate function for studyplan builders.
type StudyPlan func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPet is the predicate function for userpet builders.
type UserPet func(*sql.Selector)

// Voucher is the predicate function for voucher builders.
type Voucher func(*sql.Selector)
