// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Institution is the predicate function for institution builders.
type Institution func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
