// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AcademicSchool is the predicate function for academicschool builders.
type AcademicSchool func(*sql.Selector)

// Accessory is the predicate function for accessory builders.
type Accessory func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Institution is the predicate function for institution builders.
type Institution func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// Redemption is the predicate function for redemption builders.
type Redemption func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPet is the predicate function for userpet builders.
type UserPet func(*sql.Selector)

// Voucher is the predicate function for voucher builders.
type Voucher func(*sql.Selector)
