// Code generated by mockery v2.28.1. DO NOT EDIT.

package ent

import (
	ent "github.com/np-inprove/server/internal/ent"
	mock "github.com/stretchr/testify/mock"
)

// MockeventOption is an autogenerated mock type for the eventOption type
type MockeventOption struct {
	mock.Mock
}

type MockeventOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockeventOption) EXPECT() *MockeventOption_Expecter {
	return &MockeventOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockeventOption) Execute(_a0 *ent.EventMutation) {
	_m.Called(_a0)
}

// MockeventOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockeventOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *ent.EventMutation
func (_e *MockeventOption_Expecter) Execute(_a0 interface{}) *MockeventOption_Execute_Call {
	return &MockeventOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockeventOption_Execute_Call) Run(run func(_a0 *ent.EventMutation)) *MockeventOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ent.EventMutation))
	})
	return _c
}

func (_c *MockeventOption_Execute_Call) Return() *MockeventOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockeventOption_Execute_Call) RunAndReturn(run func(*ent.EventMutation)) *MockeventOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockeventOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockeventOption creates a new instance of MockeventOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockeventOption(t mockConstructorTestingTNewMockeventOption) *MockeventOption {
	mock := &MockeventOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
