// Code generated by mockery v2.28.1. DO NOT EDIT.

package ent

import (
	ent "github.com/np-inprove/server/internal/ent"
	mock "github.com/stretchr/testify/mock"
)

// MockreactionOption is an autogenerated mock type for the reactionOption type
type MockreactionOption struct {
	mock.Mock
}

type MockreactionOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockreactionOption) EXPECT() *MockreactionOption_Expecter {
	return &MockreactionOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockreactionOption) Execute(_a0 *ent.ReactionMutation) {
	_m.Called(_a0)
}

// MockreactionOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockreactionOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *ent.ReactionMutation
func (_e *MockreactionOption_Expecter) Execute(_a0 interface{}) *MockreactionOption_Execute_Call {
	return &MockreactionOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockreactionOption_Execute_Call) Run(run func(_a0 *ent.ReactionMutation)) *MockreactionOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ent.ReactionMutation))
	})
	return _c
}

func (_c *MockreactionOption_Execute_Call) Return() *MockreactionOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockreactionOption_Execute_Call) RunAndReturn(run func(*ent.ReactionMutation)) *MockreactionOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockreactionOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockreactionOption creates a new instance of MockreactionOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockreactionOption(t mockConstructorTestingTNewMockreactionOption) *MockreactionOption {
	mock := &MockreactionOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
