// Code generated by mockery v2.28.1. DO NOT EDIT.

package ent

import (
	ent "github.com/np-inprove/server/internal/ent"
	mock "github.com/stretchr/testify/mock"
)

// MockinstitutionOption is an autogenerated mock type for the institutionOption type
type MockinstitutionOption struct {
	mock.Mock
}

type MockinstitutionOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockinstitutionOption) EXPECT() *MockinstitutionOption_Expecter {
	return &MockinstitutionOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockinstitutionOption) Execute(_a0 *ent.InstitutionMutation) {
	_m.Called(_a0)
}

// MockinstitutionOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockinstitutionOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *ent.InstitutionMutation
func (_e *MockinstitutionOption_Expecter) Execute(_a0 interface{}) *MockinstitutionOption_Execute_Call {
	return &MockinstitutionOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockinstitutionOption_Execute_Call) Run(run func(_a0 *ent.InstitutionMutation)) *MockinstitutionOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ent.InstitutionMutation))
	})
	return _c
}

func (_c *MockinstitutionOption_Execute_Call) Return() *MockinstitutionOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockinstitutionOption_Execute_Call) RunAndReturn(run func(*ent.InstitutionMutation)) *MockinstitutionOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockinstitutionOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockinstitutionOption creates a new instance of MockinstitutionOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockinstitutionOption(t mockConstructorTestingTNewMockinstitutionOption) *MockinstitutionOption {
	mock := &MockinstitutionOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
