// Code generated by mockery v2.28.1. DO NOT EDIT.

package ent

import (
	context "context"

	ent "github.com/np-inprove/server/internal/ent"
	mock "github.com/stretchr/testify/mock"
)

// MockRollbacker is an autogenerated mock type for the Rollbacker type
type MockRollbacker struct {
	mock.Mock
}

type MockRollbacker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRollbacker) EXPECT() *MockRollbacker_Expecter {
	return &MockRollbacker_Expecter{mock: &_m.Mock}
}

// Rollback provides a mock function with given fields: _a0, _a1
func (_m *MockRollbacker) Rollback(_a0 context.Context, _a1 *ent.Tx) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Tx) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRollbacker_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockRollbacker_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *ent.Tx
func (_e *MockRollbacker_Expecter) Rollback(_a0 interface{}, _a1 interface{}) *MockRollbacker_Rollback_Call {
	return &MockRollbacker_Rollback_Call{Call: _e.mock.On("Rollback", _a0, _a1)}
}

func (_c *MockRollbacker_Rollback_Call) Run(run func(_a0 context.Context, _a1 *ent.Tx)) *MockRollbacker_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ent.Tx))
	})
	return _c
}

func (_c *MockRollbacker_Rollback_Call) Return(_a0 error) *MockRollbacker_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRollbacker_Rollback_Call) RunAndReturn(run func(context.Context, *ent.Tx) error) *MockRollbacker_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRollbacker interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRollbacker creates a new instance of MockRollbacker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRollbacker(t mockConstructorTestingTNewMockRollbacker) *MockRollbacker {
	mock := &MockRollbacker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
