// Code generated by ent, DO NOT EDIT.

package prize

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/np-inprove/server/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Prize {
	return predicate.Prize(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Prize {
	return predicate.Prize(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Prize {
	return predicate.Prize(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Prize {
	return predicate.Prize(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Prize {
	return predicate.Prize(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Prize {
	return predicate.Prize(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Prize {
	return predicate.Prize(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldDescription, v))
}

// PointsRequired applies equality check predicate on the "points_required" field. It's identical to PointsRequiredEQ.
func PointsRequired(v int) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldPointsRequired, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Prize {
	return predicate.Prize(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Prize {
	return predicate.Prize(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Prize {
	return predicate.Prize(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Prize {
	return predicate.Prize(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Prize {
	return predicate.Prize(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Prize {
	return predicate.Prize(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Prize {
	return predicate.Prize(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Prize {
	return predicate.Prize(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Prize {
	return predicate.Prize(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Prize {
	return predicate.Prize(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Prize {
	return predicate.Prize(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Prize {
	return predicate.Prize(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Prize {
	return predicate.Prize(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Prize {
	return predicate.Prize(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Prize {
	return predicate.Prize(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Prize {
	return predicate.Prize(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Prize {
	return predicate.Prize(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Prize {
	return predicate.Prize(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Prize {
	return predicate.Prize(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Prize {
	return predicate.Prize(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Prize {
	return predicate.Prize(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Prize {
	return predicate.Prize(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Prize {
	return predicate.Prize(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Prize {
	return predicate.Prize(sql.FieldContainsFold(FieldDescription, v))
}

// PointsRequiredEQ applies the EQ predicate on the "points_required" field.
func PointsRequiredEQ(v int) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldPointsRequired, v))
}

// PointsRequiredNEQ applies the NEQ predicate on the "points_required" field.
func PointsRequiredNEQ(v int) predicate.Prize {
	return predicate.Prize(sql.FieldNEQ(FieldPointsRequired, v))
}

// PointsRequiredIn applies the In predicate on the "points_required" field.
func PointsRequiredIn(vs ...int) predicate.Prize {
	return predicate.Prize(sql.FieldIn(FieldPointsRequired, vs...))
}

// PointsRequiredNotIn applies the NotIn predicate on the "points_required" field.
func PointsRequiredNotIn(vs ...int) predicate.Prize {
	return predicate.Prize(sql.FieldNotIn(FieldPointsRequired, vs...))
}

// PointsRequiredGT applies the GT predicate on the "points_required" field.
func PointsRequiredGT(v int) predicate.Prize {
	return predicate.Prize(sql.FieldGT(FieldPointsRequired, v))
}

// PointsRequiredGTE applies the GTE predicate on the "points_required" field.
func PointsRequiredGTE(v int) predicate.Prize {
	return predicate.Prize(sql.FieldGTE(FieldPointsRequired, v))
}

// PointsRequiredLT applies the LT predicate on the "points_required" field.
func PointsRequiredLT(v int) predicate.Prize {
	return predicate.Prize(sql.FieldLT(FieldPointsRequired, v))
}

// PointsRequiredLTE applies the LTE predicate on the "points_required" field.
func PointsRequiredLTE(v int) predicate.Prize {
	return predicate.Prize(sql.FieldLTE(FieldPointsRequired, v))
}

// DiscriminatorEQ applies the EQ predicate on the "discriminator" field.
func DiscriminatorEQ(v Discriminator) predicate.Prize {
	return predicate.Prize(sql.FieldEQ(FieldDiscriminator, v))
}

// DiscriminatorNEQ applies the NEQ predicate on the "discriminator" field.
func DiscriminatorNEQ(v Discriminator) predicate.Prize {
	return predicate.Prize(sql.FieldNEQ(FieldDiscriminator, v))
}

// DiscriminatorIn applies the In predicate on the "discriminator" field.
func DiscriminatorIn(vs ...Discriminator) predicate.Prize {
	return predicate.Prize(sql.FieldIn(FieldDiscriminator, vs...))
}

// DiscriminatorNotIn applies the NotIn predicate on the "discriminator" field.
func DiscriminatorNotIn(vs ...Discriminator) predicate.Prize {
	return predicate.Prize(sql.FieldNotIn(FieldDiscriminator, vs...))
}

// HasInstitution applies the HasEdge predicate on the "institution" edge.
func HasInstitution() predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InstitutionTable, InstitutionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstitutionWith applies the HasEdge predicate on the "institution" edge with a given conditions (other predicates).
func HasInstitutionWith(preds ...predicate.Institution) predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		step := newInstitutionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRedemptionUsers applies the HasEdge predicate on the "redemption_users" edge.
func HasRedemptionUsers() predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, RedemptionUsersTable, RedemptionUsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedemptionUsersWith applies the HasEdge predicate on the "redemption_users" edge with a given conditions (other predicates).
func HasRedemptionUsersWith(preds ...predicate.User) predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		step := newRedemptionUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPrizeRedemptions applies the HasEdge predicate on the "prize_redemptions" edge.
func HasPrizeRedemptions() predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, PrizeRedemptionsTable, PrizeRedemptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrizeRedemptionsWith applies the HasEdge predicate on the "prize_redemptions" edge with a given conditions (other predicates).
func HasPrizeRedemptionsWith(preds ...predicate.PrizeRedemptions) predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		step := newPrizeRedemptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Prize) predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Prize) predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Prize) predicate.Prize {
	return predicate.Prize(func(s *sql.Selector) {
		p(s.Not())
	})
}
