name: ci

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Set GOROOT
      run: echo "GOROOT=$(go env GOROOT)" > "$GITHUB_ENV"

    - name: Lint
      uses: golangci/golangci-lint-action@v3.5.0
      with:
        version: latest
        args: --timeout 30m

    - name: Build
      run: go build -v cmd/main.go

    - name: Test
      run: go test -v ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
