name: deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    if: github.ref_name == 'main'
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a np-inprove-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  build-staging:
    if: github.ref_name == 'staging'
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a np-inprove-server-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: ${{ env.FLY_APP }}

